---

- name: kubespark hdfs repo
  git:
    repo: https://github.com/apache-spark-on-k8s/kubernetes-HDFS
    dest: ~/kubernetes-HDFS

- name: Create namenode label
  shell: kubectl label nodes k8s-node1 --overwrite hdfs-namenode-selector=hdfs-namenode-0
  args:
    chdir: ~/kubernetes-HDFS/charts/hdfs-namenode-k8s/

- name: Install namenode
  shell: helm install -n hdfs-namenode --set nameNodeHostPath=/hdfs-name hdfs-namenode-k8s
  args:
    chdir: ~/kubernetes-HDFS/charts

- name: Ensure namenode is running and ready
  pause:
    minutes: 2

- name: Create datanode label
  shell: kubectl label node k8s-node1 --overwrite hdfs-datanode-exclude=yes
  args:
    chdir: ~/kubernetes-HDFS/charts/hdfs-datanode-k8s/

- name: Install datanode
  shell: helm install -n hdfs-datanode --set "dataNodeHostPath={/hdfs-data}" hdfs-datanode-k8s
  args:
    chdir: ~/kubernetes-HDFS/charts

- name: Ensure datanode is running and ready
  pause:
    minutes: 2
