---

- name: Zeppelin repo
  git:
    repo: https://github.com/banzaicloud/zeppelin
    version: spark-interpreter-k8s
    dest: ~/zeppelin
    force: yes

- name: Install maven
  apt: name=maven state=installed update_cache=true force=yes
  become: yes

- name: Compile Zeppelin
  shell: mvn org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single -B -T 1 -P apache-release -q
  args:
    executable: /bin/bash
    chdir: ~/zeppelin/zeppelin-distribution

- name: generate zeppelin Dockerfile
  template:
    src: templates/dockerfile.j2
    dest: ~/zeppelin/zeppelin-distribution/target/zeppelin-0.8.0-SNAPSHOT/Dockerfile

- name: Docker Image
  shell: |
    docker pull {{ kubezeppelin_dockerlogin }}/zeppelin-server:{{ kubezeppelin_dockertag }};
    if (($? != 0)); then
      docker login -u {{ kubezeppelin_dockerlogin }} -p {{ kubezeppelin_dockerpassword }};
      docker build -t {{ kubezeppelin_dockerlogin }}/zeppelin-server .;
      docker tag $(docker images {{ kubezeppelin_dockerlogin }}/zeppelin-server -q | tr -d "\n") {{ kubezeppelin_dockerlogin }}/zeppelin-server:{{ kubezeppelin_dockertag }};
      docker push {{ kubezeppelin_dockerlogin }}/zeppelin-server:{{ kubezeppelin_dockertag }};
    fi
  args:
    executable: /bin/bash
    chdir: ~/zeppelin/zeppelin-distribution/target/zeppelin-0.8.0-SNAPSHOT

- name: Zeppelin svc yaml
  template:
    src: templates/zeppelin-service.yaml.j2
    dest: ~/zeppelin/zeppelin-service.yaml

- name: Launch zeppelin zvc
  shell: kubectl create -f zeppelin-service.yaml
  args:
    chdir: ~/zeppelin

- name: Zeppelin server yaml
  template:
    src: templates/zeppelin-server.yaml.j2
    dest: ~/zeppelin/zeppelin-server.yaml

- name: Launch zeppelin server
  shell: kubectl create -f zeppelin-server.yaml
  args:
    chdir: ~/zeppelin

- name: UGLY !!! Give admin role to default user, to be changed !!!
  shell: kubectl create clusterrolebinding default --clusterrole cluster-admin --serviceaccount=default:default

- name: zeppelin dashboard
  debug:
    msg: "You can reach the zeppelin webui with http://{{ ansible_host }}:31298/"
  when: kubernetes_node_type == 'admin'
