---
- hosts:
    - master
    - nodes
  serial: 1
  become: false
  strategy: linear
  roles:
    - role: base
    - role: docker
      become: true
    - role: kubernetes
      become: true
    - role: k8s
    - role: kubeceph
  pre_tasks:
    - name: Ensure gitmodules update
      local_action: command git submodule update --init --recursive

- hosts: master
  serial: 1
  become: false
  strategy: linear
  roles:
    - java
    - helm
    - kubedashboard
    - kubecephcluster
    - kubezookeeper
    - kubehdfs
    - kubespark
    - kubestorm
    #- kubezeppelin
    - kubelastic
    - kubekafka
    - kubehadoop
